name: hopher
version: 0.1.0.0

license: GPL
description: Please see the README on GitHub at <https://github.com/hyperreal-gopher/hopher#readme>
github: "hyperreal-gopher/hopher"

## These fields might be useful to fill out in the future
# author:
# copyright:
# synopsis:

dependencies:
  - base >= 4.7 && < 5
  - brick
  - text
  - bytestring
  - network-simple
  - split
  - vty

library:
  source-dirs: src

executables:
  hopher:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hopher
