name: waffle
version: 0.1.0.0

license: GPL
description: Please see the README on GitHub at <https://github.com/hyperreal-gopher/waffle#readme>
github: "hyperreal-gopher/waffle"

## These fields might be useful to fill out in the future
# author:
# copyright:
# synopsis:

dependencies:
  - base >= 4.7 && < 5
  - brick
  - text
  - bytestring
  - microlens
  - open-browser
  - utf8-string
  - directory
  - filepath
  - temporary
  - containers
  - vector
  - network-simple
  - split
  - vty

data-files: data/help.txt

library:
  source-dirs: src

executables:
  waffle:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - waffle
